Make GPG commit signing optional + Git commit author configurable

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,12 +29,20 @@ inputs:
   CROWDIN_GITHUB_TOKEN:
     description: GitHub token for checkout and Crowdin
     required: true
+  COMMITTER_NAME:
+    description: Git Committer name
+    required: true
+  COMMITTER_EMAIL:
+    description: Git Committer email
+    required: true
   SWF_GPG_PRIVATE_KEY:
     description: GPG private key
-    required: true
+    default: ""
+    required: false
   SWF_GPG_PASSPHRASE:
     description: GPG passphrase
-    required: true
+    default: ""
+    required: false
 
 runs:
   using: "composite"
@@ -71,7 +79,8 @@ runs:
         CROWDIN_PERSONAL_TOKEN: ${{ inputs.CROWDIN_PERSONAL_TOKEN }}
         GITHUB_TOKEN: ${{ inputs.CROWDIN_GITHUB_TOKEN }}
 
-    - name: Import GPG key
+    - name: Import GPG key for commit signing
+      if: ${{ inputs.SWF_GPG_PRIVATE_KEY != '' }}
       uses: crazy-max/ghaction-import-gpg@v6
       with:
         gpg_private_key: ${{ inputs.SWF_GPG_PRIVATE_KEY }}
@@ -82,13 +91,15 @@ runs:
     - name: Merge translation to ${{ inputs.PROJECT_BRANCH }}
       shell: bash
       run: |
+        if [ -z "${{ inputs.COMMITTER_EMAIL }}"] || [ -z "${{ inputs.COMMITTER_NAME }}" ]; then
+          echo "COMMITTER_EMAIL and COMMITTER_NAME are required"
+          exit 1
+        fi
         sudo chown -R $USER:$USER .
         git fetch origin integration/${{ inputs.PROJECT_VERSION }}-translation
         git checkout ${{ inputs.PROJECT_BRANCH }} -f
         git reset --hard origin/${{ inputs.PROJECT_BRANCH }}
         git clean -fdx
-        git config --global user.email "exo-swf@exoplatform.com"
-        git config --global user.name "eXo Software Factory"
         git merge --squash origin/integration/${{ inputs.PROJECT_VERSION }}-translation 2>&1
         git checkout origin/${{ inputs.PROJECT_BRANCH }} -- crowdin.yml
         if git status | grep -q "nothing to commit"; then
@@ -97,6 +108,11 @@ runs:
           git commit -m "Merge Translations"
           git push origin
         fi
+      env:
+        GIT_AUTHOR_NAME: ${{ inputs.COMMITTER_NAME }}
+        GIT_AUTHOR_EMAIL: ${{ inputs.COMMITTER_EMAIL }}
+        GIT_COMMITTER_NAME: ${{ inputs.COMMITTER_NAME }}
+        GIT_COMMITTER_EMAIL: ${{ inputs.COMMITTER_EMAIL }}
 branding:
   icon: "anchor"
   color: "gray-dark"
